# ROOT CONFIGURATION
watch_stylesheet: true
watch_config: true
debug: false

# TRAY MENU KOMOREBI
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"

# BARS CONFIGURATION
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 8
      left: 8
      bottom: 0
      right: 8
    widgets:
      left: [
          # "win_button",
          # "update_check",
          "wallpapers",
          "apps",
          "taskbar",
          "komorebi_active_layout",
          "active_window",
        ]
      center: ["komorebi_workspaces"]
      right: [
          # "whkd",
          "traffic",
          # "wifi",
          "media",
          # "memory",
          # "cpu",
          # "language",
          "obs",
          "weather",
          "volume",
          "battery",
          "clock",
          "power_menu",
        ]

widgets:
  # MEDIA WIDGET
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\uf001</span> {title}"
      label_alt: "<span>\uf001</span> {artist}"
      max_field_size:
        label: 15
        label_alt: 15
      show_thumbnail: false
      controls_only: false
      controls_left: false
      hide_empty: true
      thumbnail_alpha: 100
      thumbnail_padding: 0
      thumbnail_corner_radius: 0
      callbacks:
        on_left: 'toggle_label'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
      icons:
        prev_track: "\ue627"
        next_track: "\ue628"
        play: "\uf5b0"
        pause: "\ue62e"

  # ACTIVE WINDOW TITLE WIDGET
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 35
      max_length_ellipsis: "..."
      monitor_exclusive: true

  # CLOCK WIDGET
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %H:%M}"
      label_alt: "{%A %d %B %Y, %H:%M}"
      # label: "{%a %d, %b %H:%M}"
      # label_alt: "{%A %d %B %Y, %H:%M}"
      # locale: 'en_EN' # Langugae for date, you can set your own, example fr_FR
      timezones: [] #Looking up time zone info from registry
      # timezones: ["America/Montreal"]

  # KOMOREBI WORKSPACES WIDGET
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "{name}"
      label_workspace_populated_btn: "\udb81\udc3e"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: true
      animation: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  # KOMOREBI ACTIVE LAYOUT WIDGET
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "UW-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      callbacks:
        on_left: "prev_layout"
        on_middle: "toggle_monocle"
        on_right: "next_layout"

  # WEATHER WIDGET
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: "{location}: Min {min_temp_c}, Max {max_temp_c}, Humidity {humidity}"
      api_key: "47187afa2a20476b914101340240411" # Get your free API key from https://www.weatherapi.com/
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: "Purwokerto, Central Java, Indonesia" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzard: "\uebaa"
        default: "\uebaa"

  # VOLUME WIDGET
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

  # POWER MENU WIDGET
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milisecond
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75", "Lock"]
        signout: ["\udb80\udf43", "Sign out"]
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        hibernate: ["\uf28e", "Hibernate"]
        cancel: ["\udb81\udf3a", "Cancel"]

  # CUSTOM APPS WIDGET
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        # - {icon: "\uf422", launch: "search"}
        - {
            icon: "\uf422",
            launch: "%userprofile%/scoop/apps/flow-launcher/current/Flow.Launcher.exe",
          }
        - { icon: "\udb84\udf55", launch: "widget" }
        - { icon: "\ue690", launch: "quick_settings" }
        - { icon: "\uf0a2", launch: "notification_center" }
        # - {icon: "\uf46a", launch: "cmd.exe /c start ms-settings:windowsupdate"}
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 4

  # TASKBAR WIDGET
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 14
      animation: true
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  # CUSTOM WINDOWS BUTTON WIDGET
  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a"
      class_name: "win-button-widget"
      callbacks:
        on_left: "exec start_menu"
        on_right: "exec explorer.exe shell:::{D20EA4E1-3957-11d2-A40B-0C5020524153}"

  # WALLPAPERS GALLERY WIDGET
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "%userprofile%/Pictures/Wallpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 220
        image_per_page: 8
        show_buttons: true
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
      run_after:
        # - "wal -s -t -e -q -n -i {image}", # Example command to run after wallpaper is updated
        # - "cmd.exe /c start /min pwsh ./yasb.ps1", # Example command to run after wallpaper is updated

  # BATTERY WIDGET
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"

  # TRAFFIC WIDGET
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\uf019</span> {download_speed}"
      label_alt: "<span>\uf093</span> {upload_speed}"
      update_interval: 1000
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd /c Taskmgr"

  # WHKD WIDGET
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"

  # WIFI/ETHERNET WIDGET
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      wifi_icons: [
          "\udb82\udd2e", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-20% strength
          "\udb82\udd22", # Icon for 21-40% strength
          "\udb82\udd25", # Icon for 41-80% strength
          "\udb82\udd28", # Icon for 81-100% strength
        ]

  # WINGET/WINDOWS UPDATE WIDGET
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      windows_update:
        enabled: false
        label: "<span>\uf0ab</span> {count}"
        interval: 60
        exclude: []
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span> {count}"
        interval: 30
        exclude: []

  # OBS WIDGET
  obs:
    type: "yasb.obs.ObsWidget"
    options:
      connection:
        host: "192.168.18.125"
        port: 4455
        password: "ev5wggnBpPWwMP1C"
      icons:
        recording: "\ueba7"
        stopped: "\ueba5"
        paused: "\ueba7"
      hide_when_not_recording: true
      blinking_icon: true

  # MEMORY WIDGET
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_free}/{virtual_mem_total}"
      label_alt: "<span>\uf4bc</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90

  # CPU WIDGET
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  # LANGUAGE INDICATOR WIDGET
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "{lang[language_code]}-{lang[country_code]}"
      label_alt: "{lang[full_name]}"
      update_interval: 5
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
